import Head from 'next/head'
import styles from '../styles/Home.module.css'
import StudentPill from '../components/StudentPill'
import AddNewStudent from '../components/AddNewStudent'
import FlexContainer from '../components/FlexContainer'
import {students} from '../dummyData'




export default function Home() {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Willies Dojo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Log In</h1>
        <div>  
          <FlexContainer> {/* Container for all students and AddNewStudent button */} 
            { students.map( student => <StudentPill student={student} /> ) }
          </FlexContainer>
        </div>
      </main> 
  
  {/* Testing testing */}
    </div>
  )
}
